### PR TITLE
change dependences and fix SOAP-ERROR

### PR DESCRIPTION
**Pull request by Triplkrypl**

### CODE REVIEW

**Review by digibeuk — CHANGES_REQUESTED** [review]
First off thanks for your contribution!

To be able to take a good look at your contribution I must ask you for what user case is this a fix?

Off the bat I have a couple of remarks about your PR:
-You have chmoded your files to 755, please revert this, it's unnecessary and bad practice.
-The PHP version bump is not something we can introduce in the current version without breaking BC. So good suggestion was not aware of the new version of dragonbe/vies. But will introduce this in a new release of this package. Would you be ok to make a seperate PR for this change? I will make a new branch for testing the next release and if everything is ok we can release it.
-internally we use Symfony coding style conventions, I see that i have not communicated this in the readme, which I will correct. But please use this coding style : https://symfony.com/doc/current/contributing/code/standards.html

**Comment by digibeuk** [comment]
one other thing, please also change the unit test if you add a new path to the code

**Comment by Triplkrypl** [comment]
Hi,
firs fix is update dependence: dragonbe/vies, in version 1.0 is bug in CZ VAT checksum and is fixed in 2.0 version, some CZ VAT is valid but checksum mark VAT as invalid.
Here is commit from dragonbe/vies.
https://github.com/DragonBe/vies/commit/7d9e2513a5be5cfc891bf86313b24e874c58894b#diff-95112eafdfcd4eb59b415711f0eb75fc

Second fix is clear error from soap service, soap library have one bad habit, if WSDL file can not be load, soap client throw Exception and in same time create php ERROR. Created Error can not be catched and this error symfony handle only in shutdown handler or error handler.
In fix i add function error_clear_last(), this function is only in php 7.

Thank for comments, permission 755 is bad idea, i dit not see it.
I will look for coding style, Is nice have written code by some rules.

I need write some issue in my repository, so i do not forget.

**Comment by digibeuk** [comment]
> Second fix is clear error from soap service, soap library have one bad habit, if WSDL file can not be load, soap client throw Exception and in same time create php ERROR. Created Error can not be catched and this error symfony handle only in shutdown handler or error handler.
> In fix i add function error_clear_last(), this function is only in php 7.

Do you have a use case with which I can reproduce this error?

**Comment by Triplkrypl** [comment]
Yes error can be reprocuced creating SoapClient object with invalid WSDL url or I tryed it on virtual machine witch is cutof from public network and url for soap service is unrechable.
I used php 7.1.

**Comment by digibeuk** [comment]
could you move the version change to a different PR and target the 1.0-release branch?

**Comment by Triplkrypl** [comment]
php version and code working only on php 7.0 reverted and new pull request with all changes is here:
https://github.com/MyOnlineStore/ViesBundle/pull/3.

**Comment by digibeuk** [comment]
closing this as all changes are now in another PR

**Pull request closed without merging**
